'use strict';
/* JWG.logistik – Reporting, Benutzer und Rechte, Einstellungen, Schnittstellen, Sicherheit, PRD-Abdeckung */

/* ---------- Reporting ---------- */
const weekStart = (iso) => { const d = parseISO(iso); const k = (d.getDay() + 6) % 7; d.setDate(d.getDate() - k); return isoDate(d); };
function deliveredAt(o) { return o.pod ? o.pod.ts : null; }
function onTime(o) { const ts = deliveredAt(o); return ts != null && ts <= at(o.delivery.date, o.delivery.to); }
function transitMin(o) { const a = o.history.find((h) => h.status === 'abgeholt'), z = deliveredAt(o); return a && z ? Math.max(0, (z - a.ts) / 60000) : null; }
view('reporting', {
  mod: 'reporting', title: 'Reporting',
  render() {
    const per = fv('r.per', '30'); const T = today();
    const inPer = (iso) => per === 'all' || (diffDays(T, iso) <= +per && diffDays(T, iso) >= -30);
    const all = scoped(DB.orders).filter((o) => o.status !== 'storniert' && o.status !== 'entwurf' && inPer(o.pickup.date) && (!fv('r.cust') || o.customerId === fv('r.cust')));
    const done = all.filter(isDone);
    const rev = sum(done, (o) => o.price), cost = sum(done, (o) => o.cost);
    const punct = done.filter((o) => deliveredAt(o)); const ot = punct.filter(onTime).length;
    const tm = done.map(transitMin).filter((x) => x != null);
    const claims = DB.claims.filter((c) => all.some((o) => o.id === c.orderId));
    const co2 = sum(done, (o) => co2Of(o.km || 0, o.goods.weight, o.type));
    const weeks = {}; all.forEach((o) => { const w = weekStart(o.pickup.date); (weeks[w] ||= { n: 0, rev: 0, cost: 0 }).n++; if (isDone(o)) { weeks[w].rev += o.price; weeks[w].cost += o.cost; } });
    const wk = Object.keys(weeks).sort();
    const byCust = {}; done.forEach((o) => { byCust[o.customerId] = (byCust[o.customerId] || 0) + o.price; });
    const topC = Object.entries(byCust).sort((a, b) => b[1] - a[1]).slice(0, 6).map(([id, v]) => ({ label: custName(id).replace(/ (GmbH|e\. V\.|KG|UG)$/, '').slice(0, 26), v, text: eur(v) }));
    const tours = scoped(DB.tours).filter((t) => inPer(t.date));
    const vstat = scoped(DB.vehicles).map((v) => { const ts = tours.filter((t) => t.vehicleId === v.id); const loads = ts.map((t) => tourLoad(t).kg / v.payload); return { v, n: ts.length, util: loads.length ? sum(loads) / loads.length : 0, km: sum(ts, (t) => scheduleTour(t).totalKm) }; });
    const dstat = scoped(DB.drivers).map((d) => { const ts = tours.filter((t) => t.driverId === d.id); const stops = ts.flatMap((t) => scheduleTour(t).stops.filter((s) => s.done && s.kind === 'D').map((s) => (s.doneTs <= at(s.addr.date || t.date, s.addr.to) ? 1 : 0))); return { d, n: ts.length, stops: sum(ts, (t) => t.seq.length), km: sum(ts, (t) => scheduleTour(t).totalKm), punct: stops.length ? (sum(stops) / stops.length) * 100 : null }; });
    const cc = {}; claims.forEach((c) => { cc[c.type] = (cc[c.type] || 0) + 1; });
    const carr = DB.partners.map((p) => { const os = DB.orders.filter((o) => o.carrier && o.carrier.partnerId === p.id && o.status !== 'storniert'); return { p, n: os.length, spend: sum(os, (o) => o.carrier.price), active: os.filter((o) => o.carrier.status !== 'geliefert').length }; });
    const openOrd = scoped(DB.orders).filter((o) => ACTIVE.includes(o.status)), openInv = DB.invoices.filter((i) => i.kind === 'rechnung' && i.status === 'offen');
    return html`${pageHead('Reporting und Statistiken', 'Kennzahlen zu Transporten, Umsatz, Kosten, Pünktlichkeit, Auslastung und Reklamationen.', html`<button type="button" class="btn" data-act="report.print">${ic('print')} Bericht drucken / PDF</button>`)}
      <div class="toolbar">${bindSel('Zeitraum (nach Abholdatum)', 'r.per', [['7', 'Letzte 7 Tage'], ['30', 'Letzte 30 Tage'], ['90', 'Letzte 90 Tage'], ['all', 'Alle Daten']])}${bindSel('Kunde', 'r.cust', [['', 'Alle Kunden'], ...DB.customers.map((c) => [c.id, c.name])])}</div>
      <div class="kpis">
        <div class="kpi" style="--k:var(--cobalt)"><small>Transporte</small><b>${all.length}</b><span>${done.length} zugestellt</span></div>
        <div class="kpi" style="--k:var(--pink)"><small>Umsatz netto</small><b>${eur(rev)}</b><span>Kosten ${eur(cost)}</span></div>
        <div class="kpi" style="--k:var(--mint)"><small>Gewinn (Deckungsbeitrag)</small><b>${eur(rev - cost)}</b><span>Marge ${rev ? nf(((rev - cost) / rev) * 100) : 0} %</span></div>
        <div class="kpi" style="--k:var(--sun)"><small>Pünktlichkeitsquote</small><b>${punct.length ? nf((ot / punct.length) * 100) : '–'} %</b><span>${ot} von ${punct.length} im Zeitfenster</span></div>
        <div class="kpi" style="--k:var(--lilac)"><small>Ø Transportdauer</small><b>${tm.length ? nf(sum(tm) / tm.length / 60, 1) : '–'} Std.</b><span>von Abholung bis Zustellung</span></div>
        <div class="kpi" style="--k:var(--coral)"><small>Reklamationsquote</small><b>${all.length ? nf((claims.length / all.length) * 100, 1) : 0} %</b><span>${claims.length} Fälle</span></div>
        <div class="kpi" style="--k:var(--navy)"><small>CO₂ (Schätzung)</small><b>${nf(co2)} kg</b><span>aller zugestellten Transporte</span></div></div>
      <div class="grid g2 mb"><section class="card"><div class="card-h"><h2>Transporte je Woche</h2></div>${wk.length ? barChart(wk.map((w) => ({ label: fDate(w).slice(0, 5), v: weeks[w].n })), { h: 200, label: 'Transporte je Woche' }) : empty('Keine Daten')}</section>
        <section class="card"><div class="card-h"><h2>Umsatz und Kosten je Woche</h2></div>${wk.length > 1 ? lineChart([{ name: 'Umsatz', data: wk.map((w) => weeks[w].rev), color: '#4F6BFF' }, { name: 'Kosten', data: wk.map((w) => weeks[w].cost), color: '#FF5A47' }], wk.map((w) => fDate(w).slice(0, 5)), { fmt: (v) => nf(v), area: true }) : empty('Zu wenig Daten für den Verlauf')}</section></div>
      <div class="grid g2 mb"><section class="card"><div class="card-h"><h2>Umsatz nach Kunde</h2></div>${topC.length ? hbars(topC) : empty('Noch kein Umsatz')}</section>
        <section class="card"><div class="card-h"><h2>Reklamationen nach Art</h2></div>${claims.length ? donut(Object.entries(cc).map(([k, v]) => ({ label: k, v })), { centerLabel: 'Fälle' }) : empty('Keine Reklamationen')}</section></div>
      <div class="grid g2 mb"><section class="card"><div class="card-h"><h2>Fahrzeugauslastung</h2><span class="muted tiny">Ø Beladung je Tour</span></div>${hbars(vstat.filter((x) => x.n).sort((a, b) => b.util - a.util).map((x) => ({ label: x.v.plate, v: x.util * 100, text: `${nf(x.util * 100)} % · ${x.n} Tour${x.n > 1 ? 'en' : ''}` })))}${vstat.every((x) => !x.n) ? empty('Keine Touren im Zeitraum') : ''}</section>
        <section class="card"><div class="card-h"><h2>Offene Aufträge und Rechnungen</h2></div><dl>${kv('Offene Aufträge', `${openOrd.length} (${eur(sum(openOrd, (o) => o.price))} netto)`)}${kv('Zur Abrechnung bereit', `${readyOrders().length} (${eur(sum(readyOrders(), (o) => o.price))} netto)`)}${kv('Offene Rechnungen', `${openInv.length} (${eur(sum(openInv, (i) => i.gross))} brutto)`)}${kv('Davon überfällig', `${openInv.filter((i) => invoiceState(i).id === 'ueberfaellig').length}`)}${kv('Offene Eingangsrechnungen', eur(sum(DB.inInvoices.filter((i) => i.status === 'offen'), (i) => i.gross)))}</dl></section></div>
      <h2 class="mb" style="font-size:1.1rem">Fahrer- und Tourenübersicht</h2>
      ${table('rep-drivers', [{ k: 'd', t: 'Fahrer', f: (x) => html`<a href="#/fahrer/${x.d.id}">${x.d.name}</a>`, s: (x) => x.d.name, x: (x) => x.d.name }, { k: 'b', t: 'Standort', f: (x) => branchName(x.d.branch), x: (x) => branchName(x.d.branch) }, { k: 'n', t: 'Touren', cls: 'num', f: (x) => x.n, s: (x) => x.n }, { k: 's', t: 'Stopps', cls: 'num', f: (x) => x.stops, s: (x) => x.stops }, { k: 'k', t: 'Kilometer', cls: 'num', f: (x) => nf(x.km), s: (x) => x.km }, { k: 'p', t: 'Pünktlich', cls: 'num', f: (x) => (x.punct == null ? '–' : `${nf(x.punct)} %`), s: (x) => (x.punct == null ? -1 : x.punct), x: (x) => (x.punct == null ? '' : nf(x.punct)) }], dstat, { sort: { k: 'n', dir: -1 }, name: 'report-fahrer', noun: 'Fahrern', noExport: false })}
      <h2 class="mt mb" style="font-size:1.1rem">Auslastung externer Frachtführer</h2>
      ${table('rep-carriers', [{ k: 'p', t: 'Frachtführer', f: (x) => html`<a href="#/partner/${x.p.id}">${x.p.name}</a>`, s: (x) => x.p.name, x: (x) => x.p.name }, { k: 'n', t: 'Aufträge gesamt', cls: 'num', f: (x) => x.n, s: (x) => x.n }, { k: 'a', t: 'Davon offen', cls: 'num', f: (x) => x.active, s: (x) => x.active }, { k: 'e', t: 'Frachtkosten netto', cls: 'num nw', f: (x) => eur(x.spend), s: (x) => x.spend, x: (x) => x.spend.toFixed(2) }, { k: 'q', t: 'Bewertung', cls: 'nw', f: (x) => `${nf(x.p.rating, 1)} · ${x.p.onTime} % pünktlich`, x: (x) => `${x.p.rating}; ${x.p.onTime}` }], carr, { sort: { k: 'e', dir: -1 }, name: 'report-frachtfuehrer', noun: 'Frachtführern' })}`;
  },
});
act('report.print', null, () => {
  const per = fv('r.per', '30'); const os = scoped(DB.orders).filter((o) => isDone(o)); const rev = sum(os, (o) => o.price), cost = sum(os, (o) => o.cost);
  openModal({ title: 'Bericht', wide: true, body: html`<div class="docbox">${docHead('Management-Bericht', fDate(NOW()))}<h3>Kennzahlen (zugestellte Transporte)</h3><table><tbody><tr><th>Transporte</th><td class="r">${os.length}</td></tr><tr><th>Umsatz netto</th><td class="r">${eur(rev)}</td></tr><tr><th>Kosten</th><td class="r">${eur(cost)}</td></tr><tr><th>Deckungsbeitrag</th><td class="r">${eur(rev - cost)}</td></tr><tr><th>Marge</th><td class="r">${rev ? nf(((rev - cost) / rev) * 100) : 0} %</td></tr><tr><th>Pünktlichkeit</th><td class="r">${os.filter((o) => deliveredAt(o)).length ? nf((os.filter(onTime).length / os.filter((o) => deliveredAt(o)).length) * 100) : '–'} %</td></tr><tr><th>Offene Rechnungen</th><td class="r">${eur(sum(DB.invoices.filter((i) => i.kind === 'rechnung' && i.status === 'offen'), (i) => i.gross))}</td></tr></tbody></table><p style="font-size:11px;color:#555">Zeitraum: ${per === 'all' ? 'alle Daten' : 'letzte ' + per + ' Tage'} · Beispieldaten</p>${docFoot()}</div>`, foot: html`<button type="button" class="btn ghost" data-act="modal.close">Schließen</button><button type="button" class="btn primary" data-act="doc.print">${ic('print')} Drucken / als PDF speichern</button>` });
});

/* ---------- Benutzer und Rechte ---------- */
const PERM_MODS = [['dashboard', 'Dashboard'], ['auftraege', 'Aufträge'], ['dispo', 'Disposition'], ['tracking', 'Sendungsverfolgung'], ['komm', 'Kommunikation'], ['reklamation', 'Reklamationen'], ['kunden', 'Kunden'], ['fahrer', 'Fahrer'], ['fuhrpark', 'Fuhrpark'], ['partner', 'Frachtführer'], ['angebote', 'Angebote'], ['abrechnung', 'Abrechnung'], ['dokumente', 'Dokumente'], ['lager', 'Lager'], ['reporting', 'Reporting'], ['roadmap', 'PRD-Abdeckung'], ['benutzer', 'Benutzer und Rechte'], ['einstellungen', 'Einstellungen'], ['schnittstellen', 'Schnittstellen'], ['sicherheit', 'Sicherheit']];
view('benutzer', {
  mod: 'benutzer', title: 'Benutzer und Rechte',
  render() {
    const tl = [['u', 'Benutzer'], ['r', 'Rollen und Rechte'], ['k', 'Kundenkonten'], ['s', 'Sicherheitsprotokoll'], ['a', 'Änderungsprotokoll']];
    const cur = UI.tab.usr || 'u'; const w = canWrite('benutzer'); let body;
    if (cur === 'u') body = html`<div class="toolbar">${w ? html`<button type="button" class="btn primary" data-act="usr.new">${ic('plus')} Neuer Benutzer</button>` : ''}</div>${table('users', [{ k: 'n', t: 'Name', f: (u) => html`<span class="row gap-s" style="flex-wrap:nowrap">${avatar(u.name)}<b>${u.name}</b></span>`, s: (u) => u.name, x: (u) => u.name }, { k: 'e', t: 'E-Mail', f: (u) => u.email, s: (u) => u.email }, { k: 'r', t: 'Rolle', cls: 'nw', f: (u) => chip((DB.roles.find((r) => r.id === u.role) || {}).name, u.role === 'admin' ? 'violet' : 'blue'), s: (u) => u.role, x: (u) => (DB.roles.find((r) => r.id === u.role) || {}).name }, { k: 'b', t: 'Standorte', f: (u) => u.branches.map(branchName).join(', '), x: (u) => u.branches.map(branchName).join(', ') }, { k: 'm', t: 'MFA', cls: 'nw', f: (u) => chip(u.mfa ? 'aktiv' : 'aus', u.mfa ? 'green' : DB.settings.security.mfaRequired ? 'red' : 'gray'), s: (u) => u.mfa, x: (u) => (u.mfa ? 'aktiv' : 'aus') }, { k: 's', t: 'Status', cls: 'nw', f: (u) => chip(u.active ? 'aktiv' : 'gesperrt', u.active ? 'green' : 'red'), s: (u) => u.active, x: (u) => (u.active ? 'aktiv' : 'gesperrt') }, { k: 'l', t: 'Letzte Anmeldung', cls: 'nw', f: (u) => fDT(u.last), s: (u) => u.last, x: (u) => fDT(u.last) }, { k: 'a', t: '', cls: 'nw', f: (u) => (w ? html`<span class="row gap-s"><button type="button" class="btn sm" data-act="usr.edit" data-id="${u.id}">Bearbeiten</button>${u.id !== curUser().id ? html`<button type="button" class="btn sm ghost" data-act="usr.lock" data-id="${u.id}">${u.active ? 'Sperren' : 'Entsperren'}</button>` : ''}</span>` : ''), noExport: true }], DB.users, { sort: { k: 'n', dir: 1 }, name: 'benutzer', noun: 'Benutzern' })}${DB.settings.security.mfaRequired && DB.users.some((u) => u.active && !u.mfa) ? html`<p class="mt">${notice('amber', 'Die Richtlinie verlangt MFA, aber nicht alle aktiven Benutzer haben sie eingerichtet.')}</p>` : ''}`;
    else if (cur === 'r') {
      body = html`<div class="card tight"><div class="tbl-wrap" style="border:0;box-shadow:none"><table class="tbl matrix"><thead><tr><th>Modul</th>${DB.roles.map((r) => html`<th>${r.name}</th>`)}</tr></thead><tbody>${PERM_MODS.map(([m, l]) => html`<tr><td class="first nolabel" data-l="">${l}</td>${DB.roles.map((r) => { const p = r.perm[m] || ''; return html`<td data-l="${r.name}"><button type="button" class="btn sm ${p === 'w' ? 'primary' : p === 'r' ? '' : 'ghost'}" data-act="perm.cycle" data-role="${r.id}" data-mod="${m}" ${r.locked || !w ? raw('disabled') : ''} aria-label="${l} für ${r.name}: ${p === 'w' ? 'ändern' : p === 'r' ? 'lesen' : 'kein Zugriff'}">${p === 'w' ? 'Ändern' : p === 'r' ? 'Lesen' : '–'}</button></td>`; })}</tr>`)}</tbody></table></div></div>
        <p class="note-demo mt">Klicke auf eine Zelle, um zwischen „–“, „Lesen“ und „Ändern“ zu wechseln. Die Rolle Administrator ist gesperrt. Wähle oben rechts einen Benutzer, um die Wirkung zu testen.</p>${w ? html`<div class="mt"><button type="button" class="btn" data-act="role.new">${ic('plus')} Neue Rolle</button></div>` : ''}`;
    } else if (cur === 'k') {
      body = html`${table('portal-acc', [{ k: 'c', t: 'Kunde', f: (c) => html`<a href="#/kunden/${c.id}">${c.name}</a>`, s: (c) => c.name, x: (c) => c.name }, { k: 'n', t: 'Kundennr.', cls: 'nw', f: (c) => c.nr, s: (c) => c.nr }, { k: 'p', t: 'Ansprechpartner (Konto)', f: (c) => (c.contacts[0] || {}).email || '–', x: (c) => (c.contacts[0] || {}).email || '' }, { k: 's', t: 'Portalzugang', cls: 'nw', f: (c) => html`<label class="switch"><input type="checkbox" data-act="portal.access" data-id="${c.id}" ${c.portalOff ? '' : raw('checked')} ${w ? '' : raw('disabled')}><i></i><span>${c.portalOff ? 'gesperrt' : 'aktiv'}</span></label>`, s: (c) => !c.portalOff, x: (c) => (c.portalOff ? 'gesperrt' : 'aktiv') }], DB.customers.filter((c) => !c.archived), { sort: { k: 'c', dir: 1 }, name: 'kundenkonten', noun: 'Konten' })}<p class="note-demo mt">Kundenkonten sehen im Portal nur eigene Aufträge, Angebote, Dokumente und Rechnungen.</p>`;
    } else if (cur === 's') {
      const rows = DB.seclog.filter((x) => !fv('sl.f') || (fv('sl.f') === 'fail' ? !x.ok : x.ok));
      body = html`<div class="toolbar">${bindSel('Ergebnis', 'sl.f', [['', 'Alle'], ['ok', 'Erfolgreich'], ['fail', 'Fehlgeschlagen']])}</div>${table('seclog', [{ k: 't', t: 'Zeit', cls: 'nw', f: (x) => fDT(x.ts), s: (x) => x.ts }, { k: 'u', t: 'Benutzer', f: (x) => x.user, s: (x) => x.user }, { k: 'e', t: 'Ereignis', f: (x) => x.event, s: (x) => x.event }, { k: 'd', t: 'Details', f: (x) => x.detail, x: (x) => x.detail }, { k: 'o', t: 'Ergebnis', cls: 'nw', f: (x) => chip(x.ok ? 'OK' : 'Fehler', x.ok ? 'green' : 'red'), s: (x) => x.ok, x: (x) => (x.ok ? 'OK' : 'Fehler') }, { k: 'i', t: 'IP (Beispiel)', cls: 'nw mono', f: (x) => x.ip, x: (x) => x.ip }], rows, { sort: { k: 't', dir: -1 }, name: 'sicherheitsprotokoll', noun: 'Einträgen' })}`;
    } else {
      const q = fv('au.q').trim().toLowerCase(); const rows = DB.audit.filter((a) => (!fv('au.e') || a.entity === fv('au.e')) && (!q || [a.user, a.ref, a.text, a.action].join(' ').toLowerCase().includes(q)));
      body = html`<div class="toolbar">${bindInp('Suche', 'au.q', 'Benutzer, Objekt, Text', { cls: 'search' })}${bindSel('Objekt', 'au.e', [['', 'Alle'], ...[...new Set(DB.audit.map((a) => a.entity))].sort()])}</div>${table('audit', [{ k: 't', t: 'Zeit', cls: 'nw', f: (a) => fDT(a.ts), s: (a) => a.ts }, { k: 'u', t: 'Benutzer', f: (a) => a.user, s: (a) => a.user }, { k: 'e', t: 'Objekt', cls: 'nw', f: (a) => a.entity, s: (a) => a.entity }, { k: 'r', t: 'Bezug', cls: 'nw', f: (a) => a.ref, s: (a) => a.ref }, { k: 'a', t: 'Aktion', cls: 'nw', f: (a) => a.action, s: (a) => a.action }, { k: 'x', t: 'Details', f: (a) => a.text, x: (a) => a.text }], rows, { sort: { k: 't', dir: -1 }, name: 'aenderungsprotokoll', noun: 'Einträgen', page: 25 })}`;
    }
    return html`${pageHead('Benutzer und Rechte', 'Benutzer, Rollen, Standortzugriff, Kundenkonten sowie Sicherheits- und Änderungsprotokoll.')}${tabs('usr', tl, 'u')}${body}`;
  },
});
function usrForm(u) {
  const f = u || { name: '', email: '', role: 'dispo', branches: ['b1'], mfa: false };
  return html`<input type="hidden" name="id" value="${u ? u.id : ''}"><div class="fgrid">${fld('Name', 'name', f.name, { req: true })}${fld('E-Mail', 'email', f.email, { type: 'email', req: true })}${fld('Rolle', 'role', f.role, { type: 'select', options: DB.roles.map((r) => [r.id, r.name]) })}<label class="chk" style="align-self:end"><input type="checkbox" name="mfa" ${f.mfa ? raw('checked') : ''}><span>Zwei-Faktor-Anmeldung (MFA) eingerichtet</span></label><div class="wide"><div class="fld"><span>Zugriff auf Standorte</span></div>${checks('branches', BRANCHES.map((b) => [b.id, b.name]), f.branches)}</div></div>`;
}
act('usr.new', 'benutzer', () => openModal({ title: 'Neuer Benutzer', form: 'usr.save', body: usrForm(null), foot: html`<button type="button" class="btn ghost" data-act="modal.close">Abbrechen</button><button class="btn primary">Anlegen</button>` }));
act('usr.edit', 'benutzer', (d) => openModal({ title: 'Benutzer bearbeiten', form: 'usr.save', body: usrForm(usr(d.id)), foot: html`<button type="button" class="btn ghost" data-act="modal.close">Abbrechen</button><button class="btn primary">Speichern</button>` }));
onSubmit('usr.save', 'benutzer', (f) => {
  if (!f.branches || !f.branches.length) return toast('Mindestens einen Standort wählen.', 'bad');
  let u = f.id ? usr(f.id) : null; const was = u && u.role;
  if (!u) { u = { id: uid('u'), active: true, last: 0 }; DB.users.push(u); }
  Object.assign(u, { name: f.name, email: f.email, role: f.role, branches: f.branches, mfa: !!f.mfa });
  audit('Benutzer', u.name, f.id ? 'bearbeitet' : 'erstellt', was && was !== f.role ? `Rolle ${was} → ${f.role}` : `Rolle ${f.role}`); secLog('Benutzer geändert', `${u.name}: ${f.role}`); closeModal(); commit(); toast('Benutzer gespeichert.', 'ok');
});
act('usr.lock', 'benutzer', (d) => { const u = usr(d.id); u.active = !u.active; audit('Benutzer', u.name, u.active ? 'entsperrt' : 'gesperrt', ''); secLog(u.active ? 'Benutzer entsperrt' : 'Benutzer gesperrt', u.name); commit(); });
act('perm.cycle', 'benutzer', (d) => { const r = DB.roles.find((x) => x.id === d.role); if (r.locked) return; const cur = r.perm[d.mod] || ''; r.perm[d.mod] = cur === '' ? 'r' : cur === 'r' ? 'w' : ''; audit('Rolle', r.name, 'Rechte', `${d.mod}: ${r.perm[d.mod] || 'kein Zugriff'}`); secLog('Rechte geändert', `${r.name}: ${d.mod} = ${r.perm[d.mod] || '–'}`); commit(); });
act('role.new', 'benutzer', () => openModal({ title: 'Neue Rolle', form: 'role.save', cls: 'small', body: html`<div class="stack">${fld('Name', 'name', '', { req: true })}${fld('Rechte kopieren von', 'from', 'lesen', { type: 'select', options: DB.roles.map((r) => [r.id, r.name]) })}</div>`, foot: html`<button type="button" class="btn ghost" data-act="modal.close">Abbrechen</button><button class="btn primary">Anlegen</button>` }));
onSubmit('role.save', 'benutzer', (f) => { const src = DB.roles.find((r) => r.id === f.from); DB.roles.push({ id: uid('r'), name: f.name, perm: { ...src.perm } }); audit('Rolle', f.name, 'erstellt', `Kopie von ${src.name}`); closeModal(); commit(); });
act('portal.access', 'benutzer', (d, el) => { const c = cust(d.id); c.portalOff = !el.checked; audit('Kunde', c.nr, 'Portalzugang', c.portalOff ? 'gesperrt' : 'aktiv'); secLog('Portalzugang', `${c.name}: ${c.portalOff ? 'gesperrt' : 'aktiv'}`); commit(); });

/* ---------- Einstellungen ---------- */
view('einstellungen', {
  mod: 'einstellungen', title: 'Einstellungen',
  render() {
    const tl = [['c', 'Unternehmen'], ['b', 'Standorte'], ['t', 'Transportarten'], ['z', 'Zuschläge und Preisregeln'], ['s', 'Status'], ['v', 'Fahrzeugtypen'], ['m', 'Vorlagen'], ['n', 'Nummernkreise'], ['l', 'Sprache und Währung'], ['d', 'Daten']];
    const cur = UI.tab.set || 'c'; const S_ = DB.settings; const w = canWrite('einstellungen'); const dis = w ? '' : 'disabled';
    const save_ = (id, inner) => html`<form data-submit="${id}" class="stack" style="max-width:980px">${inner}${w ? html`<div><button class="btn primary">${ic('check')} Speichern</button></div>` : html`<p class="muted tiny">Nur lesen: Dir fehlt das Recht „Einstellungen ändern“.</p>`}</form>`;
    let body;
    if (cur === 'c') { const c = S_.company; body = save_('set.company', html`<div class="fgrid">${fld('Firmenname', 'name', c.name, { req: true, cls: 'w2' })}${fld('Handelsregister', 'legal', c.legal, { cls: 'w2' })}${fld('USt-IdNr.', 'vatId', c.vatId)}${fld('Straße', 'street', c.street)}${fld('PLZ', 'zip', c.zip)}${fld('Ort', 'city', c.city)}${fld('Telefon', 'phone', c.phone)}${fld('E-Mail', 'email', c.email, { type: 'email' })}${fld('Web', 'web', c.web)}${fld('IBAN', 'iban', c.iban)}${fld('BIC', 'bic', c.bic)}</div>`); }
    else if (cur === 'b') body = html`<div class="grid g3">${BRANCHES.map((b) => html`<section class="card"><div class="card-h"><h2>${b.name}</h2>${b.hq ? chip('Zentrale', 'violet') : ''}</div><dl>${kv('Adresse', html`${b.street}<br>${b.zip} ${b.city}`)}${kv('Telefon', b.phone)}${kv('Fahrer', DB.drivers.filter((d) => d.branch === b.id).length)}${kv('Fahrzeuge', DB.vehicles.filter((v) => v.branch === b.id).length)}${kv('Aufträge', DB.orders.filter((o) => o.branch === b.id).length)}</dl></section>`)}</div>${w ? html`<div class="mt"><button type="button" class="btn primary" data-act="branch.new">${ic('plus')} Standort hinzufügen</button></div>` : ''}<p class="note-demo mt">Standorte trennen Fahrer, Fahrzeuge, Touren und Aufträge. Benutzer sehen nur die Standorte, die ihnen zugewiesen sind. Die Kopfleiste filtert die Ansicht.</p>`;
    else if (cur === 't') body = save_('set.types', html`<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Transportart</th><th class="num">Grundpreis €</th><th class="num">€ je km</th><th class="num">€ je kg</th><th class="num">Mindestpreis €</th><th class="num">max. kg</th><th class="num">CO₂ kg/tkm</th></tr></thead><tbody>${S_.transportTypes.map((t) => html`<tr><td data-l="Art"><input name="name_${t.id}" value="${t.name}" ${raw(dis)} aria-label="Name ${t.id}"></td>${[['base', t.base, '0.01'], ['perKm', t.perKm, '0.01'], ['perKg', t.perKg, '0.001'], ['min', t.min, '0.01'], ['maxKg', t.maxKg, '0.1'], ['co2', t.co2, '0.01']].map(([k, v, st]) => html`<td data-l="${k}" class="num"><input type="number" name="${k}_${t.id}" value="${v}" step="${st}" min="0" ${raw(dis)} style="width:100px;text-align:right" aria-label="${k} ${t.id}"></td>`)}</tr>`)}</tbody></table></div><p class="muted tiny">Preis = max(Mindestpreis, Grundpreis + km × €/km + frachtpflichtige kg × €/kg). Frachtpflichtig ist das größere von Gewicht und Volumen × 250 kg/m³.</p>`);
    else if (cur === 'z') { const s = S_.surcharges; body = save_('set.surcharges', html`<div class="fgrid">${fld('Expresszuschlag (%)', 'expressPct', s.expressPct, { type: 'number', step: '0.5' })}${fld('Prioritätszuschlag „Hoch“ (%)', 'hochPct', s.hochPct, { type: 'number', step: '0.5' })}${fld('Dieselzuschlag (%)', 'dieselPct', s.dieselPct, { type: 'number', step: '0.5' })}${fld('Maut (€ je km)', 'tollPerKm', s.tollPerKm, { type: 'number', step: '0.01' })}${fld('Wartezeit (€ je Stunde)', 'waitPerHour', s.waitPerHour, { type: 'number', step: '1' })}${fld('Freie Wartezeit (Min.)', 'freeWaitMin', s.freeWaitMin, { type: 'number', step: '5' })}${fld('Straßenfaktor (Luftlinie → Straße)', 'roadFactor', s.roadFactor, { type: 'number', step: '0.01', min: 1, max: 2 })}</div><fieldset><legend>Zusatzleistungen (Festpreise)</legend><div class="fgrid">${S_.extras.map((e) => fld(e.name, 'ex_' + e.id, e.fix, { type: 'number', step: '0.5', min: 0 }))}</div></fieldset>`); }
    else if (cur === 's') body = save_('set.status', html`<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Status</th><th>Anzeigename</th><th>Farbe</th><th>Vorschau</th></tr></thead><tbody>${S_.statuses.map((s) => html`<tr><td data-l="Status" class="mono">${s.id}</td><td data-l="Name"><input name="sn_${s.id}" value="${s.name}" required ${raw(dis)}></td><td data-l="Farbe"><select name="st_${s.id}" ${raw(dis)}>${optList(TONES, s.tone)}</select></td><td data-l="Vorschau">${chip(s.name, s.tone)}</td></tr>`)}</tbody></table></div><p class="muted tiny">Die Status-IDs sind fest verdrahtet, weil Disposition und Fahrer-App sie steuern. Namen und Farben sind frei wählbar.</p>`);
    else if (cur === 'v') body = save_('set.vtypes', html`<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Fahrzeugtyp</th><th class="num">Nutzlast kg</th><th class="num">Volumen m³</th><th class="num">Kosten €/km</th><th class="num">CO₂ kg/km</th></tr></thead><tbody>${S_.vehicleTypes.map((t) => html`<tr><td data-l="Typ"><input name="vn_${t.id}" value="${t.name}" ${raw(dis)}></td>${[['payload', t.payload, '10'], ['volume', t.volume, '1'], ['perKm', t.perKm, '0.01'], ['co2', t.co2, '0.01']].map(([k, v, st]) => html`<td data-l="${k}" class="num"><input type="number" name="${k}_${t.id}" value="${v}" step="${st}" min="0" style="width:100px;text-align:right" ${raw(dis)}></td>`)}</tr>`)}</tbody></table></div><p class="muted tiny">Erforderliche Fahrerlaubnis je Typ: ${S_.vehicleTypes.map((t) => `${t.name.split(' ')[0]} ${t.req.join('/')}`).join(' · ')}. Gilt für neue Fahrzeuge dieses Typs.</p>`);
    else if (cur === 'm') { const tid = fv('set.tpl', S_.templates[0].id); const t = S_.templates.find((x) => x.id === tid) || S_.templates[0]; const sample = DB.orders.find((o) => o.status === 'geplant') || DB.orders[0]; body = html`<div class="toolbar">${bindSel('Vorlage', 'set.tpl', S_.templates.map((x) => [x.id, x.name]))}</div><div class="grid g2">${save_('set.tpl', html`<input type="hidden" name="id" value="${t.id}">${fld('Betreff', 'subject', t.subject, { req: true })}${fld('Text', 'body', t.body, { type: 'textarea', rows: 10 })}<p class="tiny muted">Platzhalter: {{auftrag}}, {{sendung}}, {{status}}, {{ansprechpartner}}, {{abholung}}, {{zustellung}}, {{eta}}, {{minuten}}, {{link}}, {{rechnung}}, {{betrag}}, {{faellig}}, {{firma}}</p>`)}<section class="card"><div class="card-h"><h2>Vorschau (Beispiel ${sample.nr})</h2></div><p><b>${fillTpl(t.subject, mailCtx(sample, { rechnung: 'R-2026-0001', betrag: eur(119), faellig: fDate(today()), minuten: 30 }))}</b></p><pre style="white-space:pre-wrap;font:inherit">${fillTpl(t.body, mailCtx(sample, { rechnung: 'R-2026-0001', betrag: eur(119), faellig: fDate(today()), minuten: 30 }))}</pre></section></div>`; }
    else if (cur === 'n') body = save_('set.numbers', html`<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Nummernkreis</th><th>Präfix (%Y = Jahr)</th><th class="num">Nächste Nummer</th><th class="num">Stellen</th><th>Beispiel</th></tr></thead><tbody>${Object.entries(S_.numbers).map(([k, r]) => html`<tr><td data-l="Kreis" class="first">${r.label}</td><td data-l="Präfix"><input name="pf_${k}" value="${r.prefix}" required ${raw(dis)}></td><td data-l="Nächste" class="num"><input type="number" name="nx_${k}" value="${r.next}" min="1" style="width:100px;text-align:right" ${raw(dis)}></td><td data-l="Stellen" class="num"><input type="number" name="dg_${k}" value="${r.digits}" min="1" max="8" style="width:80px;text-align:right" ${raw(dis)}></td><td data-l="Beispiel" class="mono">${fmtNo(r, r.next)}</td></tr>`)}</tbody></table></div><p class="muted tiny">Neue Aufträge, Angebote und Rechnungen verwenden diese Nummern fortlaufend. Bitte Nummern nicht zurücksetzen, wenn schon Belege existieren.</p>`);
    else if (cur === 'l') body = save_('set.locale', html`<div class="fgrid">${fld('Sprache der Oberfläche', 'lang', 'de', { type: 'select', options: [['de', 'Deutsch (aktiv)']] })}${fld('Währung', 'currency', 'EUR', { type: 'select', options: [['EUR', 'Euro (EUR)']] })}${fld('Umsatzsteuersatz (%)', 'vat', S_.vat, { type: 'number', min: 0, max: 30, step: '0.5' })}</div><p class="note-demo">Weitere Sprachen (Englisch, Polnisch, Türkisch) und Währungen sind als Erweiterung geplant, siehe PRD-Abdeckung. Datums- und Zahlenformat folgen der deutschen Schreibweise.</p>`);
    else body = html`<div class="grid g2"><section class="card"><div class="card-h"><h2>Demo-Daten</h2></div><p>Setzt alle Aufträge, Touren, Kunden und Einstellungen auf den Ausgangszustand mit frischen Beispieldaten zurück.</p><div class="mt-s"><button type="button" class="btn danger" data-act="demo.reset" ${w ? '' : raw('disabled')}>${ic('refresh')} Demo-Daten zurücksetzen</button></div></section><section class="card"><div class="card-h"><h2>Sicherung</h2></div><p>Alle Daten als JSON-Datei sichern oder wiederherstellen.</p><div class="row mt-s"><button type="button" class="btn" data-act="backup.export">${ic('download')} Backup laden</button><button type="button" class="btn" data-act="backup.import" ${w ? '' : raw('disabled')}>${ic('upload')} Backup einspielen</button></div></section></div>`;
    return html`${pageHead('Einstellungen und Stammdaten', 'Unternehmensdaten, Standorte, Preisregeln, Status, Vorlagen und Nummernkreise.')}${tabs('set', tl, 'c')}${body}`;
  },
});
const numOr = (v, d) => (v === '' || isNaN(+v) ? d : +v);
onSubmit('set.company', 'einstellungen', (f) => { Object.assign(DB.settings.company, f); audit('Einstellung', 'Unternehmen', 'bearbeitet', 'Unternehmensdaten'); commit(); toast('Gespeichert.', 'ok'); });
onSubmit('set.types', 'einstellungen', (f) => { DB.settings.transportTypes.forEach((t) => { t.name = f['name_' + t.id] || t.name; ['base', 'perKm', 'perKg', 'min', 'maxKg', 'co2'].forEach((k) => { t[k] = numOr(f[k + '_' + t.id], t[k]); }); }); audit('Einstellung', 'Transportarten', 'bearbeitet', 'Preise geändert'); commit(); toast('Preise gespeichert. Neue Berechnungen verwenden sie sofort.', 'ok'); });
onSubmit('set.surcharges', 'einstellungen', (f) => { const s = DB.settings.surcharges; ['expressPct', 'hochPct', 'dieselPct', 'tollPerKm', 'waitPerHour', 'freeWaitMin', 'roadFactor'].forEach((k) => { s[k] = numOr(f[k], s[k]); }); DB.settings.extras.forEach((e) => { e.fix = numOr(f['ex_' + e.id], e.fix); }); audit('Einstellung', 'Zuschläge', 'bearbeitet', ''); commit(); toast('Gespeichert.', 'ok'); });
onSubmit('set.status', 'einstellungen', (f) => { DB.settings.statuses.forEach((s) => { s.name = f['sn_' + s.id] || s.name; s.tone = f['st_' + s.id] || s.tone; }); audit('Einstellung', 'Status', 'bearbeitet', ''); commit(); toast('Gespeichert.', 'ok'); });
onSubmit('set.vtypes', 'einstellungen', (f) => { DB.settings.vehicleTypes.forEach((t) => { t.name = f['vn_' + t.id] || t.name; ['payload', 'volume', 'perKm', 'co2'].forEach((k) => { t[k] = numOr(f[k + '_' + t.id], t[k]); }); }); audit('Einstellung', 'Fahrzeugtypen', 'bearbeitet', ''); commit(); toast('Gespeichert.', 'ok'); });
onSubmit('set.tpl', 'einstellungen', (f) => { const t = DB.settings.templates.find((x) => x.id === f.id); t.subject = f.subject; t.body = f.body; audit('Einstellung', 'Vorlagen', 'bearbeitet', t.name); commit(); toast('Vorlage gespeichert.', 'ok'); });
onSubmit('set.numbers', 'einstellungen', (f) => { Object.entries(DB.settings.numbers).forEach(([k, r]) => { r.prefix = f['pf_' + k] || r.prefix; r.next = Math.max(1, numOr(f['nx_' + k], r.next)); r.digits = clamp(numOr(f['dg_' + k], r.digits), 1, 8); }); audit('Einstellung', 'Nummernkreise', 'bearbeitet', ''); commit(); toast('Gespeichert.', 'ok'); });
onSubmit('set.locale', 'einstellungen', (f) => { DB.settings.vat = numOr(f.vat, 19); audit('Einstellung', 'Steuer', 'bearbeitet', `MwSt. ${DB.settings.vat} %`); commit(); toast('Gespeichert.', 'ok'); });
act('branch.new', 'einstellungen', () => openModal({ title: 'Standort hinzufügen', form: 'branch.save', cls: 'small', body: html`<div class="stack">${fld('Name', 'name', '', { req: true })}${fld('Stadt', 'city', 'Köln', { type: 'select', options: CITIES.map((c) => c.name) })}${fld('Straße', 'street', '', { req: true })}${fld('Telefon', 'phone', '', { type: 'tel' })}</div>`, foot: html`<button type="button" class="btn ghost" data-act="modal.close">Abbrechen</button><button class="btn primary">Hinzufügen</button>` }));
onSubmit('branch.save', 'einstellungen', (f) => { const c = CITY[f.city]; const b = { id: 'b' + (BRANCHES.length + 1), name: f.name, street: f.street, zip: c.zip, city: f.city, phone: f.phone, lat: c.lat, lon: c.lon }; BRANCHES.push(b); BRANCH_GEO[b.id] = { lat: c.lat, lon: c.lon }; (DB.settings.extraBranches ||= []).push(b); audit('Einstellung', 'Standorte', 'erstellt', f.name); closeModal(); commit(); toast('Standort hinzugefügt.', 'ok'); });
act('demo.reset', 'einstellungen', () => confirmBox('Alle Änderungen gehen verloren und die Beispieldaten werden neu erzeugt. Fortfahren?', 'Zurücksetzen', () => { localStorage.removeItem(DRAFT_KEY); resetDemo(); }));
act('backup.export', null, () => { DB.lastBackup = NOW(); save(); download(`jwg-logistik-backup-${today()}.json`, JSON.stringify(DB), 'application/json'); toast('Backup heruntergeladen.', 'ok'); render(); });
act('backup.import', 'einstellungen', () => openModal({ title: 'Backup einspielen', form: 'backup.import', cls: 'small', body: html`<p class="mb">Die aktuellen Daten werden ersetzt.</p>${fld('JSON-Datei', 'file', '', { type: 'file', req: true, attrs: 'accept="application/json,.json"' })}`, foot: html`<button type="button" class="btn ghost" data-act="modal.close">Abbrechen</button><button class="btn danger">Einspielen</button>` }));
onSubmit('backup.import', 'einstellungen', async (f) => { try { const db = JSON.parse(await f.file[0].text()); if (!db || db.v !== 1 || !Array.isArray(db.orders) || !db.settings) throw new Error('Format'); DB = db; DB.dirty = true; save(); closeModal(); render(); toast('Backup eingespielt.', 'ok'); } catch (e) { toast('Die Datei ist kein gültiges JWG.logistik-Backup.', 'bad'); } });

/* ---------- Schnittstellen und Integrationen ---------- */
view('schnittstellen', {
  mod: 'schnittstellen', title: 'Schnittstellen',
  render() {
    const w = canWrite('schnittstellen'); const I = DB.settings.integrations;
    const shop = readShopOrders(); const fresh = shop.filter((s) => s && s.no && !DB.shopSeen.includes(s.no));
    const shopOrders = DB.orders.filter((o) => o.source === 'shop' && o.shopNo);
    return html`${pageHead('Schnittstellen und Integrationen', 'Anbindung an Shop, Karten, Telematik, Buchhaltung, ERP, E-Mail und Partner. Hier ist klar gekennzeichnet, was echt funktioniert und was simuliert ist.')}
      <section class="card mb"><div class="card-h"><h2>${ic('box')} JWG.onlineshop</h2>${chip('funktioniert im Browser', 'green')}</div>
        <p>Bestellungen aus dem JWG.onlineshop legen automatisch einen Auftrag mit Sendungsnummer an. Das klappt, wenn Shop und Logistik-App <b>auf derselben Domain im selben Browser</b> laufen (der Shop schreibt die Bestellung lokal, die App liest sie). Zwischen zwei Servern bräuchte es eine API.</p>
        <div class="row mt-s"><label class="switch"><input type="checkbox" data-act="shop.auto" ${DB.settings.autoImportShop ? raw('checked') : ''} ${w ? '' : raw('disabled')}><i></i><span>Bestellungen automatisch übernehmen</span></label><span class="tiny muted">${fresh.length} wartend · ${shopOrders.length} übernommen · ${shop.length} im Shop-Speicher</span></div>
        <div class="row mt-s"><button type="button" class="btn primary" data-act="shop.import" ${w ? '' : raw('disabled')}>${ic('download')} Jetzt übernehmen</button><button type="button" class="btn" data-act="shop.sim" ${w ? '' : raw('disabled')}>${ic('plus')} Beispielbestellung simulieren</button><button type="button" class="btn ghost" data-act="shop.paste" ${w ? '' : raw('disabled')}>JSON einfügen</button><a class="btn ghost" href="../onlineshop/">Zum Shop ${ic('external')}</a></div></section>
      <div class="grid g3 mb">${Object.entries(I).filter(([k]) => k !== 'shop').map(([k, x]) => html`<section class="card"><div class="card-h"><h2>${x.name}</h2>${chip(x.real ? 'funktioniert' : 'Simulation', x.real ? 'green' : 'amber')}</div><p class="muted">${x.desc}</p><div class="mt-s"><label class="switch"><input type="checkbox" data-act="int.toggle" data-k="${k}" ${x.on ? raw('checked') : ''} ${w ? '' : raw('disabled')}><i></i><span>${x.on ? 'aktiviert' : 'aus'}</span></label></div></section>`)}</div>
      <div class="grid g2 mb"><section class="card"><div class="card-h"><h2>Import und Export</h2></div><ul class="list"><li>${ic('download')}<div class="grow"><b>Aufträge als CSV</b><div class="tiny muted">Semikolon-getrennt, öffnet direkt in Excel</div></div><button type="button" class="btn sm" data-act="exp.orders">Exportieren</button></li><li>${ic('download')}<div class="grow"><b>Kunden als CSV</b></div><button type="button" class="btn sm" data-act="exp.customers">Exportieren</button></li><li>${ic('upload')}<div class="grow"><b>Aufträge aus CSV importieren</b><div class="tiny muted">Spalten: Kundennummer; Abholort; Abholstraße; Zielort; Zielstraße; Datum; Beschreibung; Gewicht; Transportart</div></div>${w ? html`<button type="button" class="btn sm" data-act="imp.orders">Importieren</button>` : ''}</li><li>${ic('file')}<div class="grow"><b>Vorlage für den CSV-Import</b></div><button type="button" class="btn sm" data-act="imp.template">Laden</button></li></ul></section>
        <section class="card"><div class="card-h"><h2>API (Entwurf)</h2>${chip('nicht aktiv', 'gray')}</div><p class="muted">Eine echte REST-API braucht einen Server. So könnte die Schnittstelle aussehen:</p><pre class="mono tiny" style="background:var(--panel2);padding:10px;border-radius:10px;overflow:auto;margin:8px 0 0">GET  /api/v1/orders?status=offen
POST /api/v1/orders
GET  /api/v1/shipments/{trackingNo}
POST /api/v1/webhooks  (status.changed)

{ "customerNo": "K-1001",
  "pickup":   { "city": "Frankfurt am Main", ... },
  "delivery": { "city": "Hamburg", ... },
  "goods":    { "weightKg": 2.4, "pieces": 1 } }</pre></section></div>`;
  },
});
act('shop.auto', 'schnittstellen', (d, el) => { DB.settings.autoImportShop = el.checked; audit('Einstellung', 'Shop-Anbindung', 'bearbeitet', el.checked ? 'automatisch' : 'manuell'); commit(); });
act('shop.import', 'schnittstellen', () => { const n = importShopOrders(false); commit(); toast(n ? `${n} Bestellung${n > 1 ? 'en' : ''} aus dem Shop übernommen.` : 'Keine neuen Bestellungen im Shop-Speicher.', n ? 'ok' : ''); });
const SAMPLE_SHOP = () => ({ no: 'JWG-' + String(Math.floor(10000 + Math.random() * 89999)), ts: NOW(), name: pickOf(['Mia Hartmann', 'Noah Krause', 'Lina Schneider', 'Elias Wolff']), email: 'kunde@example.com', street: 'Beispielweg ' + (1 + Math.floor(Math.random() * 40)), zip: pickOf(['20095', '80331', '50667', '10115', '70173', '04109']), city: '', country: 'DE', items: [{ pid: 'hoodie', color: 'marine', size: 'M', qty: 1 }, { pid: 'cap', color: 'tanne', size: 'Einheitsgröße', qty: 1 }], ship: Math.random() < 0.3 ? 'express' : 'std', total: 113 });
const pickOf = (a) => a[Math.floor(Math.random() * a.length)];
act('shop.sim', 'schnittstellen', () => { const s = SAMPLE_SHOP(); s.city = (CITIES.find((c) => c.zip === s.zip) || CITIES[0]).name; const list = readShopOrders(); list.push(s); lsSet(SHOP_KEY, JSON.stringify(list)); const n = importShopOrders(false); commit(); toast(`Beispielbestellung ${s.no} wurde als Auftrag übernommen.`, 'ok'); void n; });
act('shop.paste', 'schnittstellen', () => openModal({ title: 'Bestellung einfügen', form: 'shop.paste', body: html`<p class="mb">Füge eine Bestellung (oder eine Liste) als JSON ein, zum Beispiel aus dem Shop-Speicher <span class="mono">jwg-shop-orders</span>.</p>${fld('JSON', 'json', JSON.stringify({ no: 'JWG-12345', name: 'Test Kunde', email: 'test@example.com', street: 'Musterweg 1', zip: '60311', city: 'Frankfurt am Main', items: [{ pid: 'tshirt', qty: 2 }], ship: 'std' }, null, 1), { type: 'textarea', rows: 10, req: true })}`, foot: html`<button type="button" class="btn ghost" data-act="modal.close">Abbrechen</button><button class="btn primary">Übernehmen</button>` }));
onSubmit('shop.paste', 'schnittstellen', (f) => { try { let j = JSON.parse(f.json); if (!Array.isArray(j)) j = [j]; if (!j.every((s) => s && s.no && Array.isArray(s.items))) throw new Error('Format'); const list = readShopOrders(); j.forEach((s) => list.push(s)); lsSet(SHOP_KEY, JSON.stringify(list)); const n = importShopOrders(false); closeModal(); commit(); toast(`${n} Bestellung${n === 1 ? '' : 'en'} übernommen.`, 'ok'); } catch (e) { toast('Das JSON passt nicht: Es braucht „no“ und „items“.', 'bad'); } });
act('int.toggle', 'schnittstellen', (d, el) => { DB.settings.integrations[d.k].on = el.checked; audit('Einstellung', 'Schnittstelle', 'bearbeitet', `${DB.settings.integrations[d.k].name}: ${el.checked ? 'an' : 'aus'}`); commit(); });
act('exp.orders', null, () => downloadCSV(`jwg-logistik-auftraege-${today()}.csv`, ['Auftrag', 'Kundennummer', 'Kunde', 'Status', 'Abholort', 'Abholdatum', 'Zielort', 'Lieferdatum', 'Ware', 'Gewicht kg', 'Transportart', 'Preis netto', 'Sendungsnummer'], scoped(DB.orders).map((o) => [o.nr, (cust(o.customerId) || {}).nr, custName(o.customerId), stat(o.status).name, o.pickup.city, o.pickup.date, o.delivery.city, o.delivery.date, o.goods.desc, String(o.goods.weight).replace('.', ','), ttype(o.type).name, o.price.toFixed(2).replace('.', ','), o.tracking])));
act('exp.customers', null, () => downloadCSV(`jwg-logistik-kunden-${today()}.csv`, ['Kundennummer', 'Name', 'Typ', 'Straße', 'PLZ', 'Ort', 'Ansprechpartner', 'E-Mail', 'Rabatt %', 'Zahlungsziel'], DB.customers.map((c) => [c.nr, c.name, c.type, c.street, c.zip, c.city, (c.contacts[0] || {}).name, (c.contacts[0] || {}).email, c.discount, c.terms])));
act('imp.template', null, () => download('jwg-logistik-import-vorlage.csv', csvOf(['Kundennummer', 'Abholort', 'Abholstraße', 'Zielort', 'Zielstraße', 'Datum', 'Beschreibung', 'Gewicht', 'Transportart'], [['K-1002', 'Frankfurt am Main', 'Hafenallee 14', 'Köln', 'Schildergasse 40', addDays(today(), 2), 'Schulbekleidung', '120', 'palette']])));
act('imp.orders', 'schnittstellen', () => openModal({ title: 'Aufträge aus CSV importieren', form: 'imp.orders', body: html`${fld('CSV-Datei (Semikolon)', 'file', '', { type: 'file', req: true, attrs: 'accept=".csv,text/csv"' })}<p class="tiny muted mt-s">Orte müssen aus der Städteliste der Demo stammen. Transportart: ${DB.settings.transportTypes.map((t) => t.id).join(', ')}.</p>`, foot: html`<button type="button" class="btn ghost" data-act="modal.close">Abbrechen</button><button class="btn primary">Importieren</button>` }));
onSubmit('imp.orders', 'schnittstellen', async (f) => {
  const text = (await f.file[0].text()).replace(/^﻿/, ''); const lines = text.split(/\r?\n/).filter((l) => l.trim()); const ok = [], err = [];
  lines.slice(1).forEach((l, i) => {
    const c = l.split(';').map((x) => x.replace(/^"|"$/g, '').trim()); const [kn, pc, ps, dc, ds, dt, desc, kg, ty] = c; const cu = DB.customers.find((x) => x.nr === kn);
    if (!cu) return err.push(`Zeile ${i + 2}: Kundennummer ${kn} unbekannt`); if (!CITY[pc] || !CITY[dc]) return err.push(`Zeile ${i + 2}: Ort unbekannt`); if (!/^\d{4}-\d{2}-\d{2}$/.test(dt)) return err.push(`Zeile ${i + 2}: Datum muss JJJJ-MM-TT sein`); if (!(+String(kg).replace(',', '.') > 0)) return err.push(`Zeile ${i + 2}: Gewicht fehlt`);
    if (!DB.settings.transportTypes.some((t) => t.id === ty)) return err.push(`Zeile ${i + 2}: Transportart ${ty} unbekannt`);
    ok.push({ customerId: cu.id, type: ty, prio: 'normal', branch: 'b1', source: 'import', historyText: 'Per CSV-Import angelegt', pName: pc === 'Frankfurt am Main' ? 'JWG Logistikzentrum Frankfurt' : cu.name, pStreet: ps, pZip: CITY[pc].zip, pCity: pc, pDate: dt, pFrom: '08:00', pTo: '17:00', dName: cu.name, dStreet: ds, dZip: CITY[dc].zip, dCity: dc, dDate: dt, dFrom: '08:00', dTo: '17:00', desc, weight: +String(kg).replace(',', '.'), volume: 0, pieces: 1, pallets: 0, extras: [] });
  });
  ok.forEach((x) => newOrderFrom(x)); closeModal(); commit();
  if (err.length) openModal({ title: `${ok.length} importiert, ${err.length} Fehler`, cls: 'small', body: html`<ul>${err.slice(0, 20).map((e) => html`<li>${e}</li>`)}</ul>`, foot: html`<button type="button" class="btn primary" data-act="modal.close">OK</button>` }); else toast(`${ok.length} Aufträge importiert.`, 'ok');
});

/* ---------- Sicherheit und Datenschutz ---------- */
view('sicherheit', {
  mod: 'sicherheit', title: 'Sicherheit und Datenschutz',
  render() {
    const sc = DB.settings.security; const w = canWrite('sicherheit');
    const expired = allDocs().filter((d) => d.src === 'Upload' && d.keepUntil < today());
    const rows = [['Sichere Anmeldung, MFA', 'Einstellungen und Anzeige vorhanden, Fahrer-App-PIN mit Sperre nach Fehlversuchen', 'Server mit Passwort-Hash, TOTP/WebAuthn, Sitzungsverwaltung'], ['Rollen und Rechte', 'Menüs, Schaltflächen und Aktionen folgen der Rolle (nur im Browser erzwungen)', 'Rechteprüfung zusätzlich im Server und in der Datenbank'], ['Verschlüsselung', 'keine: Daten liegen im Browser-Speicher', 'TLS, Verschlüsselung der Datenbank und Dateiablage'], ['Sichere Dokumentenspeicherung', 'Dokumente liegen im Browser (bis 250 KB)', 'Objektspeicher mit Zugriffsprotokoll, Virenscan, Versionen'], ['Backups', 'JSON-Export und -Import von Hand', 'automatische, getestete Backups mit Aufbewahrung'], ['Protokollierung', 'Änderungs- und Sicherheitsprotokoll funktionieren', 'manipulationssicheres Log, Export in SIEM'], ['Lösch- und Aufbewahrungsfristen', 'Fristen je Dokumenttyp, Löschsperre bei Uploads', 'automatische Löschläufe, Sperrvermerke, Nachweise'], ['Datenschutz, Standortdaten', 'Einwilligung je Fahrer, Position nur bei laufender Tour und Freigabe', 'Rechtsgrundlage, Betriebsvereinbarung, Auskunft und Löschung'], ['Mandantentrennung', 'Standort-Filter und Benutzerzuordnung', 'getrennte Mandanten in der Datenbank, eigene Schlüssel']];
    return html`${pageHead('Sicherheit und Datenschutz', 'Richtlinien, Fristen, Standortdaten und der ehrliche Stand: Was die Demo kann und was ein Produktivbetrieb braucht.')}
      <div class="grid g2 mb"><section class="card"><div class="card-h"><h2>Anmelderichtlinie</h2></div><form data-submit="sec.save" class="stack"><label class="switch"><input type="checkbox" name="mfaRequired" ${sc.mfaRequired ? raw('checked') : ''} ${w ? '' : raw('disabled')}><i></i><span>MFA für alle Benutzer verlangen</span></label><div class="fgrid">${fld('Sitzungsdauer (Min.)', 'sessionMin', sc.sessionMin, { type: 'number', min: 5 })}${fld('Mindestlänge Passwort', 'pwMin', sc.pwMin, { type: 'number', min: 8 })}${fld('Sperre nach Fehlversuchen', 'lockAfter', sc.lockAfter, { type: 'number', min: 3, max: 10 })}${fld('Standortdaten löschen nach (Tage)', 'locRetentionDays', sc.locRetentionDays, { type: 'number', min: 1 })}</div><label class="switch"><input type="checkbox" name="locConsentRequired" ${sc.locConsentRequired ? raw('checked') : ''} ${w ? '' : raw('disabled')}><i></i><span>Standortübermittlung nur mit Einwilligung des Fahrers</span></label>${w ? html`<div><button class="btn primary">Speichern</button></div>` : ''}</form><p class="note-demo mt-s">Die Sperre nach Fehlversuchen wirkt in der Fahrer-App. Passwort- und Sitzungsregeln greifen erst mit einem Server.</p></section>
        <section class="card"><div class="card-h"><h2>Aufbewahrung und Löschung</h2></div><form data-submit="sec.ret" class="stack"><div class="fgrid">${DB.settings.retention.map((r) => fld(r.type + ' (Jahre)', 'ret_' + r.type, r.years, { type: 'number', min: 1, max: 30 }))}</div>${w ? html`<div><button class="btn primary">Fristen speichern</button></div>` : ''}</form><p class="mt-s">${expired.length ? notice('amber', `${expired.length} hochgeladene Dokumente haben die Frist überschritten und können gelöscht werden (Menü Dokumente).`) : 'Keine hochgeladenen Dokumente mit abgelaufener Frist.'}</p></section></div>
      <div class="grid g2 mb"><section class="card"><div class="card-h"><h2>Standortdaten der Fahrer</h2></div><ul class="list">${DB.drivers.map((d) => html`<li>${avatar(d.name)}<div class="grow"><a href="#/fahrer/${d.id}">${d.name}</a></div>${chip(d.consent ? 'Einwilligung erteilt' : 'keine Einwilligung', d.consent ? 'green' : 'red')}</li>`)}</ul><p class="tiny muted mt-s">Positionen werden in der Demo nicht gespeichert, sondern aus dem Tourverlauf berechnet. Im Echtbetrieb gilt die Löschfrist von ${sc.locRetentionDays} Tagen.</p></section>
        <section class="card"><div class="card-h"><h2>Sicherung und Protokolle</h2></div><dl>${kv('Letztes Backup', DB.lastBackup ? fDT(DB.lastBackup) : 'noch keines')}${kv('Änderungsprotokoll', `${DB.audit.length} Einträge`)}${kv('Sicherheitsprotokoll', `${DB.seclog.length} Einträge`)}</dl><div class="row mt-s"><button type="button" class="btn" data-act="backup.export">${ic('download')} Backup laden</button><a class="btn ghost" href="#/benutzer">Protokolle ansehen</a></div></section></div>
      <section class="card"><div class="card-h"><h2>Umsetzungsstand: Demo und Produktion</h2></div><div class="tbl-wrap" style="box-shadow:none"><table class="tbl"><thead><tr><th>Anforderung</th><th>In dieser Demo</th><th>Für den Echtbetrieb nötig</th></tr></thead><tbody>${rows.map((r) => html`<tr><td data-l="Anforderung" class="first">${r[0]}</td><td data-l="Demo">${r[1]}</td><td data-l="Produktion">${r[2]}</td></tr>`)}</tbody></table></div></section>`;
  },
});
onSubmit('sec.save', 'sicherheit', (f) => { const sc = DB.settings.security; sc.mfaRequired = !!f.mfaRequired; sc.locConsentRequired = !!f.locConsentRequired; ['sessionMin', 'pwMin', 'lockAfter', 'locRetentionDays'].forEach((k) => { sc[k] = numOr(f[k], sc[k]); }); audit('Einstellung', 'Sicherheit', 'bearbeitet', `MFA Pflicht: ${sc.mfaRequired ? 'ja' : 'nein'}`); secLog('Richtlinie geändert', 'Sicherheitseinstellungen'); commit(); toast('Gespeichert.', 'ok'); });
onSubmit('sec.ret', 'sicherheit', (f) => { DB.settings.retention.forEach((r) => { r.years = numOr(f['ret_' + r.type], r.years); }); audit('Einstellung', 'Aufbewahrung', 'bearbeitet', ''); commit(); toast('Fristen gespeichert.', 'ok'); });

/* ---------- PRD-Abdeckung und Erweiterungen ---------- */
view('roadmap', {
  mod: 'roadmap', title: 'PRD-Abdeckung',
  render() {
    const S = { voll: ['Umgesetzt', 'green'], teil: ['Teilweise', 'amber'], sim: ['Simuliert', 'blue'], plan: ['Geplant', 'gray'] };
    const prd = [
      ['1', 'Dashboard', 'dashboard', 'voll', 'KPIs, Status, Verspätungen, Abholungen, Fahrer, Fahrzeuge, Umsatz, Aufgaben'], ['2', 'Auftragsmanagement', 'auftraege', 'voll', 'Anlegen, bearbeiten, kopieren, stornieren, Nummernkreis, Zeitfenster, Zusatzleistungen, Bestätigung, Filter'],
      ['3', 'Disposition und Tourenplanung', 'dispo', 'voll', 'Drag-and-drop, Konfliktprüfung, Mehrstopp-Touren, Karte (schematisch), neu zuweisen'], ['4', 'Kundenverwaltung (CRM)', 'kunden', 'voll', 'Stammdaten, Ansprechpartner, Adressen, Konditionen, Historie, Archiv'],
      ['5', 'Fahrerverwaltung', 'fahrer', 'voll', 'Profile, Abwesenheiten, Nachweise mit Ablauf, Einsatzzeiten, Touren'], ['6', 'Fuhrparkverwaltung', 'fuhrpark', 'voll', 'Fahrzeuge, Termine, Kosten, Defekte, Sperren und Freigeben'],
      ['7', 'Fahrer-App', 'fahrer-app', 'sim', 'Im Browser: Anmeldung, Touren, Unterschrift, Fotos, Offline-Warteschlange. Keine native App, kein Hintergrund-GPS, kein echtes Push'], ['8', 'Sendungsverfolgung', 'tracking', 'sim', 'Status, ETA, Verlauf, öffentlicher Link. Position wird aus dem Tourverlauf simuliert'],
      ['9', 'Kundenportal', 'portal', 'sim', 'Anfragen, Angebote annehmen, Sendungen, Dokumente, Reklamationen. Anmeldung nur als Demo-Auswahl'], ['10', 'Frachtführer und Partner', 'partner', 'voll', 'Profile, Preise, Vergabe, Annahme und Ablehnung (Antworten werden simuliert)'],
      ['11', 'Angebots- und Preisverwaltung', 'angebote', 'voll', 'Kalkulation, Kundentarife, Zuschläge, PDF-Druck, Umwandlung, Verlauf'], ['12', 'Dokumentenmanagement', 'dokumente', 'teil', 'Erzeugen, Upload, Zuordnung, Suche, Frist, Rechte. Speicher nur im Browser'],
      ['13', 'Abrechnung', 'abrechnung', 'voll', 'Rechnungen, Gutschriften, Storno, Mahnstufen, Eingangsrechnungen, Erlös/Kosten, CSV-Export'], ['14', 'Lager und Warenverwaltung', 'lager', 'voll', 'Bestände, Bewegungen, Umlagerung, Inventur, Zuordnung zum Auftrag'],
      ['15', 'Kommunikation', 'komm', 'sim', 'Postfach, Vorlagen, Automatik, Erinnerungen. E-Mail und Push landen im Versandprotokoll'], ['16', 'Reklamationen und Schäden', 'reklamation', 'voll', 'Fälle, Fotos, Verantwortliche, Maßnahmen, Verlauf, Gutschrift'],
      ['17', 'Reporting und Statistiken', 'reporting', 'voll', 'Kennzahlen, Diagramme, Tabellen mit CSV-Export, Druck/PDF'], ['18', 'Benutzer und Rechteverwaltung', 'benutzer', 'teil', 'Benutzer, Rollen-Matrix, Standorte, Protokolle. Rechte nur im Browser erzwungen'],
      ['19', 'Einstellungen und Stammdaten', 'einstellungen', 'voll', 'Firma, Standorte, Preise, Status, Fahrzeugtypen, Vorlagen, Nummernkreise'], ['20', 'Schnittstellen und Integrationen', 'schnittstellen', 'teil', 'Shop-Anbindung und CSV-Import/Export echt. Telematik, Buchhaltung, ERP, API sind Platzhalter'],
      ['21', 'Sicherheit und Datenschutz', 'sicherheit', 'teil', 'Richtlinien, Einwilligungen, Fristen, Protokolle. Verschlüsselung, MFA, Backups brauchen einen Server'], ['22', 'Übergreifende Anforderungen', 'dashboard', 'voll', 'Suche (/), Filter, Sortierung, responsiv, Export, Konflikthinweise, Änderungshistorie, Standorte, Dunkelmodus'],
      ['23', 'Optionale Erweiterungen', 'roadmap', 'teil', 'Siehe unten'],
    ];
    const ext = [['Tourenoptimierung', 'voll', 'Disposition › „Optimieren“ ordnet Stopps nach dem kürzesten Weg und achtet darauf, dass jede Abholung vor ihrer Zustellung liegt.', 'dispo'], ['KI-Dispositionsvorschläge', 'sim', 'Disposition › „Zuweisen“ empfiehlt die Tour mit den wenigsten Konflikten und Mehr-Kilometern. Das ist eine Regel, kein KI-Modell.', 'dispo'], ['Echtzeit-ETA und Verspätungsprognose', 'sim', 'ETA aus Fahrzeit, Stopps und Wartezeiten, neu berechnet bei jeder Anzeige. Verspätungen lösen Hinweise aus.', 'tracking'], ['CO₂-Berechnung', 'voll', 'Schätzung je Auftrag, Tour und im Reporting (Faktoren in den Einstellungen).', 'reporting'], ['Dokumentenerkennung', 'sim', 'Uploads werden über Auftrags- oder Sendungsnummer im Dateinamen zugeordnet. Keine Texterkennung.', 'dokumente'], ['Predictive Maintenance', 'sim', 'Wartungsprognose im Fuhrpark aus Termin und Tageskilometern. Keine Telematikdaten.', 'fuhrpark'], ['Frachtenbörse und Ausschreibungen', 'plan', 'Eigene Aufträge anbieten, Gebote vergleichen. Braucht Marktplatz-Anbindung und Partner.', null], ['Zoll- und Exportdokumentation', 'plan', 'Zollanmeldung und Ausfuhrpapiere. Braucht Behörden-Schnittstellen.', null], ['Dynamische Preise', 'plan', 'Preise nach Auslastung und Nachfrage. Grundlage sind die Preisregeln in den Einstellungen.', 'einstellungen'], ['Erweiterte Lagerverwaltung', 'plan', 'Lagerplätze, Chargen, Mindesthaltbarkeit, Kommissionierung.', 'lager'], ['Mehrsprachigkeit', 'plan', 'Englisch, Polnisch und Türkisch für Fahrer-App und Portal.', 'einstellungen']];
    const c = (k) => prd.filter((r) => r[3] === k).length;
    return html`${pageHead('PRD-Abdeckung', 'Alle 23 Punkte des Pflichtenhefts mit ehrlichem Stand. Diese Demo läuft komplett im Browser, ohne Server.')}
      <div class="kpis"><div class="kpi" style="--k:var(--mint)"><small>Umgesetzt</small><b>${c('voll')}</b><span>funktionieren komplett mit Beispieldaten</span></div><div class="kpi" style="--k:var(--cobalt)"><small>Simuliert</small><b>${c('sim')}</b><span>Verhalten echt, Daten oder Geräte simuliert</span></div><div class="kpi" style="--k:var(--sun)"><small>Teilweise</small><b>${c('teil')}</b><span>Server nötig für Vollständigkeit</span></div></div>
      ${table('prd', [{ k: 'n', t: 'Nr.', cls: 'num nw', f: (r) => r[0], s: (r) => +r[0] }, { k: 'm', t: 'Modul', f: (r) => (r[2] && VIEWS[r[2]] ? html`<a href="#/${r[2]}">${r[1]}</a>` : r[1]), s: (r) => r[1], x: (r) => r[1] }, { k: 's', t: 'Stand', cls: 'nw', f: (r) => chip(...S[r[3]]), s: (r) => r[3], x: (r) => S[r[3]][0] }, { k: 'd', t: 'Was funktioniert', f: (r) => r[4], x: (r) => r[4] }], prd, { sort: { k: 'n', dir: 1 }, page: 30, name: 'prd-abdeckung', noun: 'Punkten' })}
      <h2 class="mt mb" style="font-size:1.2rem">Optionale Erweiterungen (Punkt 23)</h2>
      <div class="grid g3">${ext.map((e) => html`<section class="card"><div class="card-h"><h2>${e[0]}</h2>${chip(...S[e[1]])}</div><p class="muted">${e[2]}</p>${e[3] ? html`<div class="mt-s"><a class="btn sm" href="#/${e[3]}">Ansehen</a></div>` : ''}</section>`)}</div>`;
  },
});
