'use strict';
/* JWG.logistik – Kundenportal (Selbstbedienung für Auftraggeber, Simulation mit Demo-Anmeldung) */

const PC = () => cust(SESS.portalCustomer);
const PORTAL_NAV = [['start', 'Übersicht'], ['auftraege', 'Aufträge'], ['angebote', 'Angebote'], ['sendungen', 'Sendungen'], ['dokumente', 'Dokumente und Rechnungen'], ['reklamationen', 'Reklamationen'], ['firma', 'Mein Unternehmen']];
const asPortal = (fn) => { const c = PC(); ACTOR = c ? c.name + ' (Portal)' : null; try { return fn(c); } finally { ACTOR = null; } };

function portalShell(sec, inner) {
  const c = PC();
  return html`<header class="pub-top"><a class="brand" href="#/portal" style="color:#fff;text-decoration:none"><svg width="34" height="34" viewBox="0 0 32 32" aria-hidden="true"><rect width="32" height="32" rx="9" fill="#2340E6"/><path d="M7 22h9a4.5 4.5 0 0 0 0-9h-1a4.5 4.5 0 0 1 0-9h10" fill="none" stroke="#FFD23F" stroke-width="3" stroke-linecap="round"/></svg><span><b>JWG.logistik</b><small>Kundenportal</small></span></a>
    <nav aria-label="Portal">${PORTAL_NAV.map(([id, l]) => html`<a href="#/portal/${id}" ${sec === id ? raw('aria-current="page"') : ''}>${l}</a>`)}</nav>
    <div class="row gap-s" style="margin-left:12px"><span class="tiny" style="color:#cfd5f5">${c.name}</span><button type="button" class="btn sm" data-act="portal.logout">Abmelden</button><a class="btn sm ghost" style="color:#cfd5f5" href="#/dashboard">Zur Verwaltung</a></div></header>
    <div class="pub-main">${inner}</div>`;
}
view('portal', {
  layout: 'portal', title: 'Kundenportal',
  render(seg) {
    const c = PC();
    if (!c) {
      return html`<header class="pub-top"><a class="brand" href="#/portal" style="color:#fff;text-decoration:none"><svg width="34" height="34" viewBox="0 0 32 32" aria-hidden="true"><rect width="32" height="32" rx="9" fill="#2340E6"/><path d="M7 22h9a4.5 4.5 0 0 0 0-9h-1a4.5 4.5 0 0 1 0-9h10" fill="none" stroke="#FFD23F" stroke-width="3" stroke-linecap="round"/></svg><span><b>JWG.logistik</b><small>Kundenportal</small></span></a><nav><a href="#/track">Sendung verfolgen</a><a href="#/dashboard">Zur Verwaltung</a></nav></header>
        <div class="pub-main"><section class="hero-track"><h1>Dein Transport, deine Übersicht</h1><p>Transporte anfragen, Angebote annehmen, Sendungen verfolgen und Rechnungen einsehen.</p></section>
        <section class="card" style="max-width:520px"><div class="card-h"><h2>Anmelden</h2></div><form data-submit="portal.login" class="stack"><label class="fld"><span>Kundenkonto (Demo-Auswahl)</span><select name="id">${DB.customers.filter((x) => !x.archived && !x.portalOff).map((x) => html`<option value="${x.id}">${x.name} (${x.nr})</option>`)}</select></label><button class="btn primary">${ic('lock')} Anmelden</button></form>
        <p class="note-demo mt">Im Echtbetrieb meldet sich jeder Kunde mit E-Mail, Passwort und zweitem Faktor an und sieht nur eigene Daten. In dieser Demo wählst du das Konto aus.</p></section></div>`;
    }
    const sec = seg[0] || 'start';
    const mine = DB.orders.filter((o) => o.customerId === c.id);
    let body;
    if (sec === 'start') {
      const active = mine.filter((o) => ['abgeholt', 'in_zustellung'].includes(o.status)), open = DB.invoices.filter((i) => i.customerId === c.id && i.status === 'offen'), qs = DB.quotes.filter((q) => q.customerId === c.id && q.status === 'versendet');
      body = html`<div class="page-h"><div><h1>Hallo ${c.contacts[0] ? c.contacts[0].name.split(' ')[0] : ''}</h1><p>${c.name} · Kundennummer ${c.nr}</p></div><a class="btn primary" href="#/portal/anfrage">${ic('plus')} Transport anfragen</a></div>
        <div class="kpis"><a class="kpi" href="#/portal/auftraege" style="--k:var(--sun)"><small>Offene Aufträge</small><b>${mine.filter((o) => ACTIVE.includes(o.status)).length}</b><span>${active.length} unterwegs</span></a><a class="kpi" href="#/portal/angebote" style="--k:var(--cobalt)"><small>Angebote zur Entscheidung</small><b>${qs.length}</b><span>warten auf deine Antwort</span></a><a class="kpi" href="#/portal/dokumente" style="--k:var(--coral)"><small>Offene Rechnungen</small><b>${eur(sum(open, (i) => i.gross))}</b><span>${open.length} Rechnung${open.length === 1 ? '' : 'en'}</span></a><a class="kpi" href="#/portal/reklamationen" style="--k:var(--mint)"><small>Reklamationen</small><b>${DB.claims.filter((x) => x.customerId === c.id && !['geloest', 'abgelehnt'].includes(x.status)).length}</b><span>in Bearbeitung</span></a></div>
        <section class="card"><div class="card-h"><h2>Aktuelle Sendungen</h2><a href="#/portal/sendungen">Alle</a></div>${mine.filter((o) => ACTIVE.includes(o.status)).length ? html`<ul class="list">${mine.filter((o) => ACTIVE.includes(o.status)).slice(0, 6).map((o) => html`<li>${statusChip(o.status)}<div class="grow"><a href="#/portal/sendungen?nr=${o.tracking}">${o.tracking}</a> · ${route(o)}<div class="tiny muted">${etaWord(o)}</div></div></li>`)}</ul>` : empty('Keine laufenden Sendungen')}</section>`;
    } else if (sec === 'auftraege') {
      body = html`<div class="page-h"><div><h1>Aufträge</h1><p>Alle Transporte deines Unternehmens.</p></div><a class="btn primary" href="#/portal/anfrage">${ic('plus')} Transport anfragen</a></div>${table('p-orders', [{ k: 'nr', t: 'Auftrag', cls: 'nw', f: (o) => html`<a href="#/portal/sendungen?nr=${o.tracking}">${o.nr}</a>`, s: (o) => o.nr }, { k: 'r', t: 'Strecke', f: (o) => route(o), s: (o) => o.pickup.city }, { k: 'd', t: 'Abholung', cls: 'nw', f: (o) => fDate(o.pickup.date), s: (o) => o.pickup.date }, { k: 'z', t: 'Zustellung', cls: 'nw', f: (o) => fDate(o.delivery.date), s: (o) => o.delivery.date }, { k: 's', t: 'Status', cls: 'nw', f: (o) => statusChip(o.status), s: (o) => o.status, x: (o) => stat(o.status).name }, { k: 'p', t: 'Preis netto', cls: 'num nw', f: (o) => eur(o.price), s: (o) => o.price }], mine, { sort: { k: 'd', dir: -1 }, name: 'meine-auftraege', noun: 'Aufträgen' })}`;
    } else if (sec === 'anfrage') {
      body = portalOrderForm(c);
    } else if (sec === 'angebote') {
      const qs = DB.quotes.filter((q) => q.customerId === c.id && q.status !== 'entwurf');
      body = html`<div class="page-h"><div><h1>Angebote</h1><p>Nimm Angebote direkt an. Daraus wird sofort ein Transportauftrag.</p></div></div>${qs.length ? html`<div class="stack">${qs.map((q) => html`<section class="card"><div class="row" style="justify-content:space-between"><div><b>${q.nr}</b> · ${q.from} → ${q.to}<div class="tiny muted">${ttype(q.type).name} · ${nf(q.weight, 1)} kg · gültig bis ${fDate(q.valid)}</div></div><div class="right"><b style="font-family:var(--font-display);font-size:1.6rem">${eur(q.net)}</b><div class="tiny muted">netto · ${quoteChip(q.status)}</div></div></div>${q.status === 'versendet' ? html`<div class="row mt-s"><button type="button" class="btn primary" data-act="quote.accept" data-id="${q.id}">${ic('check')} Angebot annehmen</button><button type="button" class="btn" data-act="quote.reject" data-id="${q.id}">Ablehnen</button><button type="button" class="btn ghost" data-act="doc.open" data-kind="quote" data-id="${q.id}">Ansehen / drucken</button></div>` : html`<div class="row mt-s"><button type="button" class="btn ghost" data-act="doc.open" data-kind="quote" data-id="${q.id}">Ansehen</button>${q.orderId ? html`<span class="tiny muted">Auftrag ${q.orderId}</span>` : ''}</div>`}</section>`)}</div>` : empty('Keine Angebote vorhanden')}`;
    } else if (sec === 'sendungen') {
      const nr = (parseRoute().q.get('nr')) || UI.f['ps.nr'] || ''; const o = nr ? mine.find((x) => [x.tracking, x.nr, x.ref].some((v) => v && v.toLowerCase() === nr.toLowerCase())) : null;
      body = html`<div class="page-h"><div><h1>Sendungen</h1><p>Suche nach Sendungsnummer, Auftragsnummer oder deiner Referenz.</p></div></div><form data-submit="portal.search" class="row mb" role="search"><label class="fld grow" style="max-width:420px"><span class="sr">Nummer</span><input name="nr" value="${nr}" placeholder="Sendungsnummer oder Referenz" required></label><button class="btn primary">${ic('search')} Suchen</button></form>
        ${nr && !o ? notice('amber', 'In deinen Aufträgen wurde nichts zu dieser Nummer gefunden.') : ''}${o ? trackPanel(o, true) : table('p-ship', [{ k: 't', t: 'Sendung', cls: 'nw', f: (x) => html`<a class="mono" href="#/portal/sendungen?nr=${x.tracking}">${x.tracking}</a>`, s: (x) => x.tracking }, { k: 'r', t: 'Strecke', f: (x) => route(x), s: (x) => x.pickup.city }, { k: 's', t: 'Status', cls: 'nw', f: (x) => statusChip(x.status), s: (x) => x.status, x: (x) => stat(x.status).name }, { k: 'e', t: 'Zustellung', cls: 'nw', f: (x) => etaWord(x), s: (x) => x.delivery.date }], mine.filter((x) => ACTIVE.includes(x.status)), { name: 'meine-sendungen', noun: 'Sendungen', empty: 'Keine laufenden Sendungen' })}`;
    } else if (sec === 'dokumente') {
      const inv = DB.invoices.filter((i) => i.customerId === c.id);
      body = html`<div class="page-h"><div><h1>Dokumente und Rechnungen</h1></div></div><div class="grid g2"><section class="card"><div class="card-h"><h2>Rechnungen</h2></div>${inv.length ? html`<ul class="list">${inv.map((i) => { const s = invoiceState(i); return html`<li>${ic('euro')}<div class="grow"><b>${i.nr}</b><div class="tiny muted">${fDate(i.date)} · fällig ${fDate(i.due)} · ${eur(i.gross)}</div></div>${chip(s.label, s.tone)}<button type="button" class="btn sm" data-act="doc.open" data-kind="invoice" data-id="${i.id}">Ansehen</button></li>`; })}</ul>` : empty('Keine Rechnungen')}</section>
        <section class="card"><div class="card-h"><h2>Liefernachweise</h2></div>${mine.filter((o) => o.pod).length ? html`<ul class="list">${mine.filter((o) => o.pod).slice(0, 12).map((o) => html`<li>${ic('file')}<div class="grow"><b>${o.nr}</b><div class="tiny muted">${o.delivery.city} · ${fDT(o.pod.ts)}</div></div><button type="button" class="btn sm" data-act="doc.open" data-kind="pod" data-id="${o.id}">Ansehen</button></li>`)}</ul>` : empty('Noch keine Zustellungen')}</section></div>`;
    } else if (sec === 'reklamationen') {
      const cs = DB.claims.filter((x) => x.customerId === c.id);
      body = html`<div class="page-h"><div><h1>Reklamationen</h1><p>Schaden, Fehlmenge oder Verspätung melden.</p></div><button type="button" class="btn primary" data-act="portal.claim">${ic('plus')} Reklamation melden</button></div>${cs.length ? html`<ul class="list card">${cs.map((x) => html`<li>${claimChip(x.status)}<div class="grow"><b>${x.nr}</b> · ${x.type} · Auftrag ${x.orderId}<div class="tiny muted">${x.text}</div></div></li>`)}</ul>` : html`<div class="card">${empty('Keine Reklamationen')}</div>`}`;
    } else {
      body = html`<div class="page-h"><div><h1>Mein Unternehmen</h1></div><button type="button" class="btn" data-act="portal.firm">${ic('edit')} Adresse ändern</button></div><div class="grid g2"><section class="card"><div class="card-h"><h2>Firmendaten</h2></div><dl>${kv('Firma', c.name)}${kv('Kundennummer', c.nr)}${kv('Adresse', html`${c.street}<br>${c.zip} ${c.city}`)}${kv('Zahlungsziel', c.terms ? c.terms + ' Tage netto' : 'sofort')}${kv('Preisliste', c.priceList + (c.discount ? `, ${c.discount} % Rabatt` : ''))}</dl></section>
        <section class="card"><div class="card-h"><h2>Ansprechpartner bei JWG</h2></div><dl>${kv('Disposition', DB.settings.company.email)}${kv('Telefon', DB.settings.company.phone)}${kv('Anschrift', html`${DB.settings.company.name}<br>${DB.settings.company.street}, ${DB.settings.company.zip} ${DB.settings.company.city}`)}</dl></section>
        <section class="card"><div class="card-h"><h2>Deine Ansprechpartner</h2></div><ul class="list">${c.contacts.map((p) => html`<li>${avatar(p.name)}<div class="grow"><b>${p.name}</b> <span class="muted">${p.role}</span><div class="tiny">${p.email} · ${p.phone}</div></div></li>`)}</ul></section></div>`;
    }
    return portalShell(sec === 'anfrage' ? 'auftraege' : sec, body);
  },
  after(seg) { if (seg[0] === 'anfrage') { const f = $('form[data-submit="portal.order"]'); if (f) { const u = () => portalPreview(f); f.addEventListener('input', u); f.addEventListener('change', u); u(); } } },
});
VIEWS.portal.form = (seg) => seg[0] === 'anfrage';
const quoteChip = (s) => chip({ entwurf: 'Entwurf', versendet: 'wartet auf Antwort', angenommen: 'angenommen', abgelehnt: 'abgelehnt', abgelaufen: 'abgelaufen' }[s] || s, { versendet: 'amber', angenommen: 'green', abgelehnt: 'red', abgelaufen: 'gray', entwurf: 'gray' }[s] || 'gray');
onSubmit('portal.login', null, (f) => { SESS.portalCustomer = f.id; saveSess(); ACTOR = cust(f.id).name + ' (Portal)'; secLog('Portal-Anmeldung', 'Erfolgreich (Demo)'); ACTOR = null; save(); location.hash = '#/portal/start'; render(); });
act('portal.logout', null, () => { SESS.portalCustomer = null; saveSess(); location.hash = '#/portal'; render(); });
onSubmit('portal.search', null, (f) => { UI.f['ps.nr'] = f.nr.trim(); location.hash = `#/portal/sendungen?nr=${encodeURIComponent(f.nr.trim())}`; });

function portalOrderForm(c) {
  const adr = c.addresses[0] || { name: c.name, street: c.street, zip: c.zip, city: c.city };
  const sec = (p, title, a, label) => html`<fieldset><legend>${title}</legend><div class="fgrid">${fld('Name / Firma', p + 'Name', a.name, { req: true })}${fld('Straße und Hausnummer', p + 'Street', a.street, { req: true })}${fld('Stadt', p + 'City', a.city, { type: 'select', options: CITIES.map((x) => x.name) })}${fld('PLZ', p + 'Zip', a.zip, { req: true, pattern: '[0-9]{5}', maxlength: 5 })}${fld('Ansprechpartner', p + 'Contact', a.contact || '')}${fld('Telefon', p + 'Phone', a.phone || '', { type: 'tel' })}${fld(label + 'datum', p + 'Date', addDays(today(), 1), { type: 'date', req: true, min: today() })}${fld('von', p + 'From', '08:00', { type: 'time' })}${fld('bis', p + 'To', p === 'p' ? '12:00' : '17:00', { type: 'time' })}</div></fieldset>`;
  return html`<div class="page-h"><div><h1>Transport anfragen</h1><p>Wir prüfen deine Anfrage und bestätigen sie. Der Preis unten ist eine Schätzung.</p></div></div>
    <form data-submit="portal.order" class="grid g21" novalidate><div>${sec('p', 'Abholung', { ...adr, contact: (c.contacts[0] || {}).name, phone: (c.contacts[0] || {}).phone }, 'Abhol')}${sec('d', 'Lieferung', { name: '', street: '', city: 'Frankfurt am Main', zip: '60311' }, 'Liefer')}
      <fieldset><legend>Ware und Transport</legend><div class="fgrid">${fld('Beschreibung', 'desc', '', { req: true, cls: 'wide' })}${fld('Gewicht (kg)', 'weight', '', { type: 'number', req: true, min: 0.1, step: '0.1' })}${fld('Volumen (m³)', 'volume', '', { type: 'number', min: 0, step: '0.01' })}${fld('Packstücke', 'pieces', 1, { type: 'number', min: 1, req: true })}${fld('davon Paletten', 'pallets', 0, { type: 'number', min: 0 })}${fld('Transportart', 'type', 'paket', { type: 'select', options: DB.settings.transportTypes.map((t) => [t.id, t.name]) })}${fld('Priorität', 'prio', 'normal', { type: 'select', options: DB.settings.priorities.map((t) => [t.id, t.name]) })}<div class="wide"><div class="fld"><span>Zusatzleistungen</span></div>${checks('extras', DB.settings.extras.filter((e) => e.fix).map((e) => [e.id, e.name]), [])}</div>${fld('Bemerkung', 'note', '', { type: 'textarea', cls: 'wide' })}</div></fieldset></div>
      <aside class="stack" style="position:sticky;top:76px;align-self:start"><section class="card"><div class="card-h"><h2>Preisschätzung</h2></div><div id="pprev"></div></section><button class="btn primary block">${ic('check')} Anfrage senden</button><a class="btn ghost block" href="#/portal/auftraege">Abbrechen</a></aside></form>`;
}
function portalPreview(form) {
  const f = formObj(form); const box = $('#pprev'); if (!box || !CITY[f.pCity] || !CITY[f.dCity]) return;
  const o = { type: f.type, prio: f.prio, extras: f.extras || [], customerId: SESS.portalCustomer, goods: { weight: +f.weight || 0, volume: +f.volume || 0, pallets: +f.pallets || 0 }, pickup: geoFor(f.pStreet || 'x', f.pCity), delivery: geoFor(f.dStreet || 'y', f.dCity) };
  const pr = calcPrice(o); const tt = ttype(f.type);
  box.innerHTML = String(html`<dl>${kv('Strecke', `${nf(pr.km)} km`)}${kv('Netto', html`<b>${eur(pr.net)}</b>`)}${kv('Brutto', eur(pr.gross))}</dl>${tt.maxKg && +f.weight > tt.maxKg ? notice('amber', `${tt.name}: maximal ${nf(tt.maxKg, 1)} kg.`) : ''}<p class="tiny muted mt-s">Dein Kundentarif (${PC().priceList}${PC().discount ? ', −' + PC().discount + ' %' : ''}) ist eingerechnet.</p>`);
}
onSubmit('portal.order', null, (f) => asPortal((c) => {
  const tt = ttype(f.type);
  if (tt.maxKg && +f.weight > tt.maxKg) return toast(`${tt.name}: maximal ${nf(tt.maxKg, 1)} kg. Bitte eine andere Transportart wählen.`, 'bad');
  if (f.dDate < f.pDate) return toast('Das Lieferdatum liegt vor dem Abholdatum.', 'bad');
  const o = newOrderFrom({ ...f, customerId: c.id, branch: 'b1', source: 'portal', by: c.name + ' (Portal)', historyText: 'Anfrage im Kundenportal gestellt', extras: f.extras || [] });
  pushNotif(`Neue Portal-Anfrage ${o.nr} von ${c.name}.`, 'info', `#/auftraege/${o.id}`); commit(); toast(`Anfrage ${o.nr} wurde gesendet.`, 'ok'); location.hash = '#/portal/auftraege';
}));
act('portal.claim', null, () => { const c = PC(); openModal({ title: 'Reklamation melden', wide: true, form: 'portal.claim', body: html`<div class="fgrid">${fld('Auftrag', 'orderId', '', { type: 'select', req: true, cls: 'wide', options: [['', '– wählen –'], ...DB.orders.filter((o) => o.customerId === c.id && !['storniert', 'entwurf'].includes(o.status)).map((o) => [o.id, `${o.nr} · ${o.pickup.city} → ${o.delivery.city}`])] })}${fld('Art', 'type', 'Schaden', { type: 'select', options: CLAIM_TYPES })}${fld('Fotos (optional)', 'files', '', { type: 'file', attrs: 'accept="image/*" multiple' })}${fld('Beschreibung', 'text', '', { type: 'textarea', req: true, cls: 'wide' })}</div>`, foot: html`<button type="button" class="btn ghost" data-act="modal.close">Abbrechen</button><button class="btn primary">Senden</button>` }); });
onSubmit('portal.claim', null, async (f) => { const photos = []; for (const file of Array.from(f.files || []).slice(0, 4)) { const p = await shrinkImage(file); if (p) photos.push(p); } asPortal((c) => { const cl = newClaim({ ...f, photos, resp: 'Lea Fischer', cost: 0 }); cl.log[0].by = c.name + ' (Portal)'; closeModal(); commit(); toast(`Reklamation ${cl.nr} wurde gemeldet.`, 'ok'); }); });
act('portal.firm', null, () => { const c = PC(); openModal({ title: 'Firmenadresse ändern', form: 'portal.firm', cls: 'small', body: html`<div class="stack">${fld('Straße', 'street', c.street, { req: true })}${fld('Stadt', 'city', c.city, { type: 'select', options: CITIES.map((x) => x.name) })}${fld('PLZ', 'zip', c.zip, { req: true, pattern: '[0-9]{5}', maxlength: 5 })}</div><p class="note-demo mt">Änderungen werden im Änderungsprotokoll festgehalten.</p>`, foot: html`<button type="button" class="btn ghost" data-act="modal.close">Abbrechen</button><button class="btn primary">Speichern</button>` }); });
onSubmit('portal.firm', null, (f) => asPortal((c) => { Object.assign(c, { street: f.street, city: f.city, zip: f.zip }); c.billing = { ...c.billing, street: f.street, city: f.city, zip: f.zip }; audit('Kunde', c.nr, 'bearbeitet', 'Firmenadresse im Portal geändert'); closeModal(); commit(); toast('Adresse gespeichert.', 'ok'); }));
